name: ArmorStandGUI
version: '${project.version}'
main: me.kiernan.armorstandgui.ArmorStandGUI
api-version: 1.17
authors: [ kiernan ]
description: A GUI that allows the player to customize an Armorstand within a GUI
commands:
  armorstand:
    description: creates an armor stand
